name: Emblazon
favicon: null
layout_spectrum: 0.26788926240988076
typography_spectrum: 0.2687713236082345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.4902606038376689
purpose: []
